### ISSUE TITLE
Duplicate Search Results due to Multiple Authors

### ISSUE THREAD

**Issue by csperlich** [stefprez/database_project#6]
searched by title for "Deacon", got two results, but the second was just a duplicate of the first. It returned the following in search results:

Title: The Book of Deacon (Volume 1)
By: 
Publisher: , 
Category: Fantasy
ISBN: 9781470008956, Price: $11.69

Title: The Book of Deacon (Volume 1)
By: 
Publisher: , 
Category: Fantasy
ISBN: 9781470008956, Price: $11.69

**Comment by stefprez** [comment]
I haven't investigated this yet, but could it be a duplicate entry in the database, or some other issue with the script? When I search with an empty search box, it's the only book that turns up twice.

**Comment by csperlich** [comment]
It has the same issue for the "Database System Concepts" book. Each of
these books have multiple authors, and an entry is being shown equal to the
number of authors for the book.

**Comment by stefprez** [comment]
Ahhh, it must be because of how I'm doing the natural join on the multiple tables. This is creating two duplicate entries in my results table. I'll see if I can remove duplicates from the results.

**Comment by stefprez** [comment]
So what's happening is the natural join is creating n rows for books that have n authors. Using the DISTINCT modifier in SQL does not handle this because the author columns are not identical. I'm not sure what the best way to handle this would be, because even if we were to remove one, as of right now, we are only showing one author per book. Maybe it's best to just remove the duplicate authors and call that an edge case that we don't handle.

**Comment by csperlich** [comment]
I'm going to take a stab at this. We have to get the book info for each isbn in the cart minus the authors, then we have to run a separate query for the author.

**Comment by stefprez** [comment]
Sounds great. Make sure to pull, I've made some changes today! Let me know if I can help at all. I'm going to start looking for more cleanup.

**Comment by csperlich** [comment]
Done, please do a little checking for me.

**Comment by stefprez** [comment]
Looks great! Nice job with that.
